### ISSUE TITLE
IOC crashes while connecting to PandA (first test at NSLS-II)

### ISSUE THREAD

**Issue by dmgav** [PandABlocks/PandABlocks-ioc#25]
This is my our first attempt to test of the IOC with PandA. I installed the IOC from the `fixes` branch as recommended and started the IOC as follows: 

```
PandABlocks-ioc softioc xf03idc-panda1.nsls2.bnl.local PANDA ./screens
```

The IOC creates a number of .bob files, but then crashes with the following message:
```
...
INFO:Description for SRGATE4:WHEN_DISABLED longer than EPICS limit of 40 characters. It will be truncated. Description: What to do with the output when Enable is low
INFO:Description for SYSTEM:EXT_CLOCK longer than EPICS limit of 40 characters. It will be truncated. Description: External sma and event receiver clock enables
INFO:Description for SYSTEM:CLK_SEL_STAT longer than EPICS limit of 40 characters. It will be truncated. Description: Read-back of EXT/event reciever clock select
ERROR:Exception while initializing softioc
Traceback (most recent call last):
  File "/home/xf03id/repos/PandABlocks-ioc/src/pandablocks_ioc/ioc.py", line 133, in create_softioc
    ).result()
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/xf03id/repos/PandABlocks-ioc/src/pandablocks_ioc/ioc.py", line 98, in _create_softioc
    (all_records, all_values_dict) = await create_records(
  File "/home/xf03id/repos/PandABlocks-ioc/src/pandablocks_ioc/ioc.py", line 1793, in create_records
    Pvi.create_pvi_records(record_prefix)
  File "/home/xf03id/repos/PandABlocks-ioc/src/pandablocks_ioc/_pvi.py", line 223, in create_pvi_records
    formatter.format(
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/dls.py", line 45, in format
    f(device, prefix, path)
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/dls.py", line 234, in format_bob
    texts = screen.screen(device.children, title).format()
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 330, in screen
    self.make_group_widget(
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 447, in make_group_widget
    group = self.group(
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 501, in group
    widgets = widgets + self.make_component_widgets(
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 545, in make_component_widgets
    widgets = list(self.component(c, column_bounds, group_widget_indent, add_label))
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 411, in component
    yield self.screen_widgets.pv_widget(
  File "/home/xf03id/conda_envs/2023-2.0-py310-tiled-panda/lib/python3.10/site-packages/pvi/_format/utils.py", line 289, in pv_widget
    return widget_factory[type(widget)](bounds, prefix + pv)
KeyError: <class 'pvi.device.TableWrite'>
```
Is the issue related to incorrect dependencies? What is the best way to debug the issue?

**Comment by AlexanderWells-diamond** [comment]
You are right, this looks like an issue in the [PVI dependency](https://github.com/epics-containers/pvi). @evalott100 @GDYendell are you able to comment further?

**Comment by GDYendell** [comment]
This is because the pvi dependency needed updating to the latest version. I have pushed the change to the fixes branch, so that should work now.

**Comment by dmgav** [comment]
Thanks @GDYendell Updating the dependency fixed the issue. The IOC starts now.
