### ISSUE TITLE
Warnings are displayed for blocks with empty tables

### ISSUE THREAD

**Issue by dmgav** [PandABlocks/PandABlocks-ioc#47]
Many warnings are displayed by the IOC each time a user switches between designs using GUI. The warnings are printed for the blocks with empty tables (in this test `SEQ2` and `PGEN2`):

```
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:TRIGGER is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:POSITION is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:TIME1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTA1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTB1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTC1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTD1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTE1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTF1 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:TIME2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTA2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTB2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTC2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTD2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTE2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record SEQ2:TABLE:OUTF2 is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
WARNING:Index 0 of record PGEN2:TABLE:POSITION is out of bounds.
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_tables.py", line 678, in _update_scalar
    scalar_val = waveform_data[index]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by dmgav** [comment]
Possible solution: to quiet down the exception the case when `len(waveform) == 0` should be processed separately by raising a dedicated exception or just by checking the condition and setting `scalar_val=0` and `sev` to `alarm.NO_ALARM` or `alarm.INVALID_ALARM`.

https://github.com/PandABlocks/PandABlocks-ioc/blob/35360f4e29a32bf7cdc54e9d1d210c52b3d3f729/src/pandablocks_ioc/_tables.py#L675-L695
